/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as LoginRouteImport } from './login'
import { Route as AppRouteRouteImport } from './app/route'
import { Route as IndexRouteImport } from './index'
import { Route as AppIndexRouteImport } from './app/index'
import { Route as InviteTokenRouteImport } from './invite.$token'
import { Route as AppImportRouteImport } from './app/import'
import { Route as AppAuditRouteImport } from './app/audit'
import { Route as ApiHealthRouteImport } from './api/health'
import { Route as AppMitgliederIndexRouteImport } from './app/mitglieder/index'
import { Route as AppDsgvoIndexRouteImport } from './app/dsgvo/index'
import { Route as AppBerichteIndexRouteImport } from './app/berichte/index'
import { Route as AppBeitragIndexRouteImport } from './app/beitrag/index'
import { Route as AppMitgliederNeuRouteImport } from './app/mitglieder/neu'
import { Route as AppMitgliederMitgliedsnummerRouteImport } from './app/mitglieder/$mitgliedsnummer'
import { Route as AppEinstellungenVereinRouteImport } from './app/einstellungen/verein'
import { Route as AppEinstellungenSmtpRouteImport } from './app/einstellungen/smtp'
import { Route as AppEinstellungenBenutzerRouteImport } from './app/einstellungen/benutzer'
import { Route as AppEinstellungenBeitragsartenRouteImport } from './app/einstellungen/beitragsarten'
import { Route as AppEinstellungenAbteilungenRouteImport } from './app/einstellungen/abteilungen'
import { Route as AppDsgvoIdRouteImport } from './app/dsgvo/$id'
import { Route as AppBerichteGeburtstageRouteImport } from './app/berichte/geburtstage'
import { Route as AppBerichteFinanzenRouteImport } from './app/berichte/finanzen'
import { Route as AppBerichteEhrungenRouteImport } from './app/berichte/ehrungen'
import { Route as AppBerichteBestandserhebungRouteImport } from './app/berichte/bestandserhebung'
import { Route as AppBerichteAbteilungsStatistikRouteImport } from './app/berichte/abteilungs-statistik'
import { Route as AppBeitragNeuRouteImport } from './app/beitrag/neu'
import { Route as AppBeitragIdRouteImport } from './app/beitrag/$id'
import { Route as AppAdminSnapshotsRouteImport } from './app/admin/snapshots'
import { Route as AppAdminErweitertRouteImport } from './app/admin/erweitert'
import { Route as ApiRpcSplatRouteImport } from './api/rpc.$'
import { Route as ApiIngestSvumsRouteImport } from './api/ingest.svums'
import { Route as ApiFilesIdRouteImport } from './api/files.$id'
import { Route as ApiCronSnapshotsRouteImport } from './api/cron.snapshots'
import { Route as ApiAuthSplatRouteImport } from './api/auth.$'
import { Route as AppMitgliederMitgliedsnummerBearbeitenRouteImport } from './app/mitglieder/$mitgliedsnummer_.bearbeiten'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMitgliederIndexRoute = AppMitgliederIndexRouteImport.update({
  id: '/mitglieder/',
  path: '/mitglieder/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDsgvoIndexRoute = AppDsgvoIndexRouteImport.update({
  id: '/dsgvo/',
  path: '/dsgvo/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBerichteIndexRoute = AppBerichteIndexRouteImport.update({
  id: '/berichte/',
  path: '/berichte/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBeitragIndexRoute = AppBeitragIndexRouteImport.update({
  id: '/beitrag/',
  path: '/beitrag/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMitgliederNeuRoute = AppMitgliederNeuRouteImport.update({
  id: '/mitglieder/neu',
  path: '/mitglieder/neu',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMitgliederMitgliedsnummerRoute =
  AppMitgliederMitgliedsnummerRouteImport.update({
    id: '/mitglieder/$mitgliedsnummer',
    path: '/mitglieder/$mitgliedsnummer',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppEinstellungenVereinRoute = AppEinstellungenVereinRouteImport.update({
  id: '/einstellungen/verein',
  path: '/einstellungen/verein',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEinstellungenSmtpRoute = AppEinstellungenSmtpRouteImport.update({
  id: '/einstellungen/smtp',
  path: '/einstellungen/smtp',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEinstellungenBenutzerRoute =
  AppEinstellungenBenutzerRouteImport.update({
    id: '/einstellungen/benutzer',
    path: '/einstellungen/benutzer',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppEinstellungenBeitragsartenRoute =
  AppEinstellungenBeitragsartenRouteImport.update({
    id: '/einstellungen/beitragsarten',
    path: '/einstellungen/beitragsarten',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppEinstellungenAbteilungenRoute =
  AppEinstellungenAbteilungenRouteImport.update({
    id: '/einstellungen/abteilungen',
    path: '/einstellungen/abteilungen',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDsgvoIdRoute = AppDsgvoIdRouteImport.update({
  id: '/dsgvo/$id',
  path: '/dsgvo/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBerichteGeburtstageRoute = AppBerichteGeburtstageRouteImport.update({
  id: '/berichte/geburtstage',
  path: '/berichte/geburtstage',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBerichteFinanzenRoute = AppBerichteFinanzenRouteImport.update({
  id: '/berichte/finanzen',
  path: '/berichte/finanzen',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBerichteEhrungenRoute = AppBerichteEhrungenRouteImport.update({
  id: '/berichte/ehrungen',
  path: '/berichte/ehrungen',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBerichteBestandserhebungRoute =
  AppBerichteBestandserhebungRouteImport.update({
    id: '/berichte/bestandserhebung',
    path: '/berichte/bestandserhebung',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppBerichteAbteilungsStatistikRoute =
  AppBerichteAbteilungsStatistikRouteImport.update({
    id: '/berichte/abteilungs-statistik',
    path: '/berichte/abteilungs-statistik',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppBeitragNeuRoute = AppBeitragNeuRouteImport.update({
  id: '/beitrag/neu',
  path: '/beitrag/neu',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBeitragIdRoute = AppBeitragIdRouteImport.update({
  id: '/beitrag/$id',
  path: '/beitrag/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminSnapshotsRoute = AppAdminSnapshotsRouteImport.update({
  id: '/admin/snapshots',
  path: '/admin/snapshots',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminErweitertRoute = AppAdminErweitertRouteImport.update({
  id: '/admin/erweitert',
  path: '/admin/erweitert',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestSvumsRoute = ApiIngestSvumsRouteImport.update({
  id: '/api/ingest/svums',
  path: '/api/ingest/svums',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesIdRoute = ApiFilesIdRouteImport.update({
  id: '/api/files/$id',
  path: '/api/files/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSnapshotsRoute = ApiCronSnapshotsRouteImport.update({
  id: '/api/cron/snapshots',
  path: '/api/cron/snapshots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMitgliederMitgliedsnummerBearbeitenRoute =
  AppMitgliederMitgliedsnummerBearbeitenRouteImport.update({
    id: '/mitglieder/$mitgliedsnummer_/bearbeiten',
    path: '/mitglieder/$mitgliedsnummer/bearbeiten',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/app/audit': typeof AppAuditRoute
  '/app/import': typeof AppImportRoute
  '/invite/$token': typeof InviteTokenRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/snapshots': typeof ApiCronSnapshotsRoute
  '/api/files/$id': typeof ApiFilesIdRoute
  '/api/ingest/svums': typeof ApiIngestSvumsRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/app/admin/erweitert': typeof AppAdminErweitertRoute
  '/app/admin/snapshots': typeof AppAdminSnapshotsRoute
  '/app/beitrag/$id': typeof AppBeitragIdRoute
  '/app/beitrag/neu': typeof AppBeitragNeuRoute
  '/app/berichte/abteilungs-statistik': typeof AppBerichteAbteilungsStatistikRoute
  '/app/berichte/bestandserhebung': typeof AppBerichteBestandserhebungRoute
  '/app/berichte/ehrungen': typeof AppBerichteEhrungenRoute
  '/app/berichte/finanzen': typeof AppBerichteFinanzenRoute
  '/app/berichte/geburtstage': typeof AppBerichteGeburtstageRoute
  '/app/dsgvo/$id': typeof AppDsgvoIdRoute
  '/app/einstellungen/abteilungen': typeof AppEinstellungenAbteilungenRoute
  '/app/einstellungen/beitragsarten': typeof AppEinstellungenBeitragsartenRoute
  '/app/einstellungen/benutzer': typeof AppEinstellungenBenutzerRoute
  '/app/einstellungen/smtp': typeof AppEinstellungenSmtpRoute
  '/app/einstellungen/verein': typeof AppEinstellungenVereinRoute
  '/app/mitglieder/$mitgliedsnummer': typeof AppMitgliederMitgliedsnummerRoute
  '/app/mitglieder/neu': typeof AppMitgliederNeuRoute
  '/app/beitrag/': typeof AppBeitragIndexRoute
  '/app/berichte/': typeof AppBerichteIndexRoute
  '/app/dsgvo/': typeof AppDsgvoIndexRoute
  '/app/mitglieder/': typeof AppMitgliederIndexRoute
  '/app/mitglieder/$mitgliedsnummer/bearbeiten': typeof AppMitgliederMitgliedsnummerBearbeitenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/app/audit': typeof AppAuditRoute
  '/app/import': typeof AppImportRoute
  '/invite/$token': typeof InviteTokenRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/snapshots': typeof ApiCronSnapshotsRoute
  '/api/files/$id': typeof ApiFilesIdRoute
  '/api/ingest/svums': typeof ApiIngestSvumsRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/app/admin/erweitert': typeof AppAdminErweitertRoute
  '/app/admin/snapshots': typeof AppAdminSnapshotsRoute
  '/app/beitrag/$id': typeof AppBeitragIdRoute
  '/app/beitrag/neu': typeof AppBeitragNeuRoute
  '/app/berichte/abteilungs-statistik': typeof AppBerichteAbteilungsStatistikRoute
  '/app/berichte/bestandserhebung': typeof AppBerichteBestandserhebungRoute
  '/app/berichte/ehrungen': typeof AppBerichteEhrungenRoute
  '/app/berichte/finanzen': typeof AppBerichteFinanzenRoute
  '/app/berichte/geburtstage': typeof AppBerichteGeburtstageRoute
  '/app/dsgvo/$id': typeof AppDsgvoIdRoute
  '/app/einstellungen/abteilungen': typeof AppEinstellungenAbteilungenRoute
  '/app/einstellungen/beitragsarten': typeof AppEinstellungenBeitragsartenRoute
  '/app/einstellungen/benutzer': typeof AppEinstellungenBenutzerRoute
  '/app/einstellungen/smtp': typeof AppEinstellungenSmtpRoute
  '/app/einstellungen/verein': typeof AppEinstellungenVereinRoute
  '/app/mitglieder/$mitgliedsnummer': typeof AppMitgliederMitgliedsnummerRoute
  '/app/mitglieder/neu': typeof AppMitgliederNeuRoute
  '/app/beitrag': typeof AppBeitragIndexRoute
  '/app/berichte': typeof AppBerichteIndexRoute
  '/app/dsgvo': typeof AppDsgvoIndexRoute
  '/app/mitglieder': typeof AppMitgliederIndexRoute
  '/app/mitglieder/$mitgliedsnummer/bearbeiten': typeof AppMitgliederMitgliedsnummerBearbeitenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/app/audit': typeof AppAuditRoute
  '/app/import': typeof AppImportRoute
  '/invite/$token': typeof InviteTokenRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/snapshots': typeof ApiCronSnapshotsRoute
  '/api/files/$id': typeof ApiFilesIdRoute
  '/api/ingest/svums': typeof ApiIngestSvumsRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/app/admin/erweitert': typeof AppAdminErweitertRoute
  '/app/admin/snapshots': typeof AppAdminSnapshotsRoute
  '/app/beitrag/$id': typeof AppBeitragIdRoute
  '/app/beitrag/neu': typeof AppBeitragNeuRoute
  '/app/berichte/abteilungs-statistik': typeof AppBerichteAbteilungsStatistikRoute
  '/app/berichte/bestandserhebung': typeof AppBerichteBestandserhebungRoute
  '/app/berichte/ehrungen': typeof AppBerichteEhrungenRoute
  '/app/berichte/finanzen': typeof AppBerichteFinanzenRoute
  '/app/berichte/geburtstage': typeof AppBerichteGeburtstageRoute
  '/app/dsgvo/$id': typeof AppDsgvoIdRoute
  '/app/einstellungen/abteilungen': typeof AppEinstellungenAbteilungenRoute
  '/app/einstellungen/beitragsarten': typeof AppEinstellungenBeitragsartenRoute
  '/app/einstellungen/benutzer': typeof AppEinstellungenBenutzerRoute
  '/app/einstellungen/smtp': typeof AppEinstellungenSmtpRoute
  '/app/einstellungen/verein': typeof AppEinstellungenVereinRoute
  '/app/mitglieder/$mitgliedsnummer': typeof AppMitgliederMitgliedsnummerRoute
  '/app/mitglieder/neu': typeof AppMitgliederNeuRoute
  '/app/beitrag/': typeof AppBeitragIndexRoute
  '/app/berichte/': typeof AppBerichteIndexRoute
  '/app/dsgvo/': typeof AppDsgvoIndexRoute
  '/app/mitglieder/': typeof AppMitgliederIndexRoute
  '/app/mitglieder/$mitgliedsnummer_/bearbeiten': typeof AppMitgliederMitgliedsnummerBearbeitenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/api/health'
    | '/app/audit'
    | '/app/import'
    | '/invite/$token'
    | '/app/'
    | '/api/auth/$'
    | '/api/cron/snapshots'
    | '/api/files/$id'
    | '/api/ingest/svums'
    | '/api/rpc/$'
    | '/app/admin/erweitert'
    | '/app/admin/snapshots'
    | '/app/beitrag/$id'
    | '/app/beitrag/neu'
    | '/app/berichte/abteilungs-statistik'
    | '/app/berichte/bestandserhebung'
    | '/app/berichte/ehrungen'
    | '/app/berichte/finanzen'
    | '/app/berichte/geburtstage'
    | '/app/dsgvo/$id'
    | '/app/einstellungen/abteilungen'
    | '/app/einstellungen/beitragsarten'
    | '/app/einstellungen/benutzer'
    | '/app/einstellungen/smtp'
    | '/app/einstellungen/verein'
    | '/app/mitglieder/$mitgliedsnummer'
    | '/app/mitglieder/neu'
    | '/app/beitrag/'
    | '/app/berichte/'
    | '/app/dsgvo/'
    | '/app/mitglieder/'
    | '/app/mitglieder/$mitgliedsnummer/bearbeiten'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/health'
    | '/app/audit'
    | '/app/import'
    | '/invite/$token'
    | '/app'
    | '/api/auth/$'
    | '/api/cron/snapshots'
    | '/api/files/$id'
    | '/api/ingest/svums'
    | '/api/rpc/$'
    | '/app/admin/erweitert'
    | '/app/admin/snapshots'
    | '/app/beitrag/$id'
    | '/app/beitrag/neu'
    | '/app/berichte/abteilungs-statistik'
    | '/app/berichte/bestandserhebung'
    | '/app/berichte/ehrungen'
    | '/app/berichte/finanzen'
    | '/app/berichte/geburtstage'
    | '/app/dsgvo/$id'
    | '/app/einstellungen/abteilungen'
    | '/app/einstellungen/beitragsarten'
    | '/app/einstellungen/benutzer'
    | '/app/einstellungen/smtp'
    | '/app/einstellungen/verein'
    | '/app/mitglieder/$mitgliedsnummer'
    | '/app/mitglieder/neu'
    | '/app/beitrag'
    | '/app/berichte'
    | '/app/dsgvo'
    | '/app/mitglieder'
    | '/app/mitglieder/$mitgliedsnummer/bearbeiten'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/api/health'
    | '/app/audit'
    | '/app/import'
    | '/invite/$token'
    | '/app/'
    | '/api/auth/$'
    | '/api/cron/snapshots'
    | '/api/files/$id'
    | '/api/ingest/svums'
    | '/api/rpc/$'
    | '/app/admin/erweitert'
    | '/app/admin/snapshots'
    | '/app/beitrag/$id'
    | '/app/beitrag/neu'
    | '/app/berichte/abteilungs-statistik'
    | '/app/berichte/bestandserhebung'
    | '/app/berichte/ehrungen'
    | '/app/berichte/finanzen'
    | '/app/berichte/geburtstage'
    | '/app/dsgvo/$id'
    | '/app/einstellungen/abteilungen'
    | '/app/einstellungen/beitragsarten'
    | '/app/einstellungen/benutzer'
    | '/app/einstellungen/smtp'
    | '/app/einstellungen/verein'
    | '/app/mitglieder/$mitgliedsnummer'
    | '/app/mitglieder/neu'
    | '/app/beitrag/'
    | '/app/berichte/'
    | '/app/dsgvo/'
    | '/app/mitglieder/'
    | '/app/mitglieder/$mitgliedsnummer_/bearbeiten'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronSnapshotsRoute: typeof ApiCronSnapshotsRoute
  ApiFilesIdRoute: typeof ApiFilesIdRoute
  ApiIngestSvumsRoute: typeof ApiIngestSvumsRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/import': {
      id: '/app/import'
      path: '/import'
      fullPath: '/app/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/mitglieder/': {
      id: '/app/mitglieder/'
      path: '/mitglieder'
      fullPath: '/app/mitglieder/'
      preLoaderRoute: typeof AppMitgliederIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dsgvo/': {
      id: '/app/dsgvo/'
      path: '/dsgvo'
      fullPath: '/app/dsgvo/'
      preLoaderRoute: typeof AppDsgvoIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/berichte/': {
      id: '/app/berichte/'
      path: '/berichte'
      fullPath: '/app/berichte/'
      preLoaderRoute: typeof AppBerichteIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/beitrag/': {
      id: '/app/beitrag/'
      path: '/beitrag'
      fullPath: '/app/beitrag/'
      preLoaderRoute: typeof AppBeitragIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/mitglieder/neu': {
      id: '/app/mitglieder/neu'
      path: '/mitglieder/neu'
      fullPath: '/app/mitglieder/neu'
      preLoaderRoute: typeof AppMitgliederNeuRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/mitglieder/$mitgliedsnummer': {
      id: '/app/mitglieder/$mitgliedsnummer'
      path: '/mitglieder/$mitgliedsnummer'
      fullPath: '/app/mitglieder/$mitgliedsnummer'
      preLoaderRoute: typeof AppMitgliederMitgliedsnummerRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/einstellungen/verein': {
      id: '/app/einstellungen/verein'
      path: '/einstellungen/verein'
      fullPath: '/app/einstellungen/verein'
      preLoaderRoute: typeof AppEinstellungenVereinRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/einstellungen/smtp': {
      id: '/app/einstellungen/smtp'
      path: '/einstellungen/smtp'
      fullPath: '/app/einstellungen/smtp'
      preLoaderRoute: typeof AppEinstellungenSmtpRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/einstellungen/benutzer': {
      id: '/app/einstellungen/benutzer'
      path: '/einstellungen/benutzer'
      fullPath: '/app/einstellungen/benutzer'
      preLoaderRoute: typeof AppEinstellungenBenutzerRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/einstellungen/beitragsarten': {
      id: '/app/einstellungen/beitragsarten'
      path: '/einstellungen/beitragsarten'
      fullPath: '/app/einstellungen/beitragsarten'
      preLoaderRoute: typeof AppEinstellungenBeitragsartenRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/einstellungen/abteilungen': {
      id: '/app/einstellungen/abteilungen'
      path: '/einstellungen/abteilungen'
      fullPath: '/app/einstellungen/abteilungen'
      preLoaderRoute: typeof AppEinstellungenAbteilungenRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dsgvo/$id': {
      id: '/app/dsgvo/$id'
      path: '/dsgvo/$id'
      fullPath: '/app/dsgvo/$id'
      preLoaderRoute: typeof AppDsgvoIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/berichte/geburtstage': {
      id: '/app/berichte/geburtstage'
      path: '/berichte/geburtstage'
      fullPath: '/app/berichte/geburtstage'
      preLoaderRoute: typeof AppBerichteGeburtstageRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/berichte/finanzen': {
      id: '/app/berichte/finanzen'
      path: '/berichte/finanzen'
      fullPath: '/app/berichte/finanzen'
      preLoaderRoute: typeof AppBerichteFinanzenRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/berichte/ehrungen': {
      id: '/app/berichte/ehrungen'
      path: '/berichte/ehrungen'
      fullPath: '/app/berichte/ehrungen'
      preLoaderRoute: typeof AppBerichteEhrungenRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/berichte/bestandserhebung': {
      id: '/app/berichte/bestandserhebung'
      path: '/berichte/bestandserhebung'
      fullPath: '/app/berichte/bestandserhebung'
      preLoaderRoute: typeof AppBerichteBestandserhebungRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/berichte/abteilungs-statistik': {
      id: '/app/berichte/abteilungs-statistik'
      path: '/berichte/abteilungs-statistik'
      fullPath: '/app/berichte/abteilungs-statistik'
      preLoaderRoute: typeof AppBerichteAbteilungsStatistikRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/beitrag/neu': {
      id: '/app/beitrag/neu'
      path: '/beitrag/neu'
      fullPath: '/app/beitrag/neu'
      preLoaderRoute: typeof AppBeitragNeuRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/beitrag/$id': {
      id: '/app/beitrag/$id'
      path: '/beitrag/$id'
      fullPath: '/app/beitrag/$id'
      preLoaderRoute: typeof AppBeitragIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/snapshots': {
      id: '/app/admin/snapshots'
      path: '/admin/snapshots'
      fullPath: '/app/admin/snapshots'
      preLoaderRoute: typeof AppAdminSnapshotsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/erweitert': {
      id: '/app/admin/erweitert'
      path: '/admin/erweitert'
      fullPath: '/app/admin/erweitert'
      preLoaderRoute: typeof AppAdminErweitertRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest/svums': {
      id: '/api/ingest/svums'
      path: '/api/ingest/svums'
      fullPath: '/api/ingest/svums'
      preLoaderRoute: typeof ApiIngestSvumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$id': {
      id: '/api/files/$id'
      path: '/api/files/$id'
      fullPath: '/api/files/$id'
      preLoaderRoute: typeof ApiFilesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/snapshots': {
      id: '/api/cron/snapshots'
      path: '/api/cron/snapshots'
      fullPath: '/api/cron/snapshots'
      preLoaderRoute: typeof ApiCronSnapshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/mitglieder/$mitgliedsnummer_/bearbeiten': {
      id: '/app/mitglieder/$mitgliedsnummer_/bearbeiten'
      path: '/mitglieder/$mitgliedsnummer/bearbeiten'
      fullPath: '/app/mitglieder/$mitgliedsnummer/bearbeiten'
      preLoaderRoute: typeof AppMitgliederMitgliedsnummerBearbeitenRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppAuditRoute: typeof AppAuditRoute
  AppImportRoute: typeof AppImportRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminErweitertRoute: typeof AppAdminErweitertRoute
  AppAdminSnapshotsRoute: typeof AppAdminSnapshotsRoute
  AppBeitragIdRoute: typeof AppBeitragIdRoute
  AppBeitragNeuRoute: typeof AppBeitragNeuRoute
  AppBerichteAbteilungsStatistikRoute: typeof AppBerichteAbteilungsStatistikRoute
  AppBerichteBestandserhebungRoute: typeof AppBerichteBestandserhebungRoute
  AppBerichteEhrungenRoute: typeof AppBerichteEhrungenRoute
  AppBerichteFinanzenRoute: typeof AppBerichteFinanzenRoute
  AppBerichteGeburtstageRoute: typeof AppBerichteGeburtstageRoute
  AppDsgvoIdRoute: typeof AppDsgvoIdRoute
  AppEinstellungenAbteilungenRoute: typeof AppEinstellungenAbteilungenRoute
  AppEinstellungenBeitragsartenRoute: typeof AppEinstellungenBeitragsartenRoute
  AppEinstellungenBenutzerRoute: typeof AppEinstellungenBenutzerRoute
  AppEinstellungenSmtpRoute: typeof AppEinstellungenSmtpRoute
  AppEinstellungenVereinRoute: typeof AppEinstellungenVereinRoute
  AppMitgliederMitgliedsnummerRoute: typeof AppMitgliederMitgliedsnummerRoute
  AppMitgliederNeuRoute: typeof AppMitgliederNeuRoute
  AppBeitragIndexRoute: typeof AppBeitragIndexRoute
  AppBerichteIndexRoute: typeof AppBerichteIndexRoute
  AppDsgvoIndexRoute: typeof AppDsgvoIndexRoute
  AppMitgliederIndexRoute: typeof AppMitgliederIndexRoute
  AppMitgliederMitgliedsnummerBearbeitenRoute: typeof AppMitgliederMitgliedsnummerBearbeitenRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppImportRoute: AppImportRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminErweitertRoute: AppAdminErweitertRoute,
  AppAdminSnapshotsRoute: AppAdminSnapshotsRoute,
  AppBeitragIdRoute: AppBeitragIdRoute,
  AppBeitragNeuRoute: AppBeitragNeuRoute,
  AppBerichteAbteilungsStatistikRoute: AppBerichteAbteilungsStatistikRoute,
  AppBerichteBestandserhebungRoute: AppBerichteBestandserhebungRoute,
  AppBerichteEhrungenRoute: AppBerichteEhrungenRoute,
  AppBerichteFinanzenRoute: AppBerichteFinanzenRoute,
  AppBerichteGeburtstageRoute: AppBerichteGeburtstageRoute,
  AppDsgvoIdRoute: AppDsgvoIdRoute,
  AppEinstellungenAbteilungenRoute: AppEinstellungenAbteilungenRoute,
  AppEinstellungenBeitragsartenRoute: AppEinstellungenBeitragsartenRoute,
  AppEinstellungenBenutzerRoute: AppEinstellungenBenutzerRoute,
  AppEinstellungenSmtpRoute: AppEinstellungenSmtpRoute,
  AppEinstellungenVereinRoute: AppEinstellungenVereinRoute,
  AppMitgliederMitgliedsnummerRoute: AppMitgliederMitgliedsnummerRoute,
  AppMitgliederNeuRoute: AppMitgliederNeuRoute,
  AppBeitragIndexRoute: AppBeitragIndexRoute,
  AppBerichteIndexRoute: AppBerichteIndexRoute,
  AppDsgvoIndexRoute: AppDsgvoIndexRoute,
  AppMitgliederIndexRoute: AppMitgliederIndexRoute,
  AppMitgliederMitgliedsnummerBearbeitenRoute:
    AppMitgliederMitgliedsnummerBearbeitenRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  InviteTokenRoute: InviteTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronSnapshotsRoute: ApiCronSnapshotsRoute,
  ApiFilesIdRoute: ApiFilesIdRoute,
  ApiIngestSvumsRoute: ApiIngestSvumsRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
