CREATE TYPE "public"."audit_action" AS ENUM('create', 'update', 'delete', 'restore');--> statement-breakpoint
CREATE TYPE "public"."audit_source" AS ENUM('ui', 'import', 'svums_push', 'system');--> statement-breakpoint
CREATE TYPE "public"."user_role" AS ENUM('admin', 'vorstand', 'readonly');--> statement-breakpoint
CREATE TYPE "public"."import_source" AS ENUM('sql_upload', 'svums_push');--> statement-breakpoint
CREATE TABLE "abteilungen" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"slug" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "abteilungen_name_unique" UNIQUE("name"),
	CONSTRAINT "abteilungen_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "member_abteilungen" (
	"member_id" uuid NOT NULL,
	"abteilung_id" uuid NOT NULL,
	"eintrittsdatum" date NOT NULL,
	"austrittsdatum" date,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "member_abteilungen_member_id_abteilung_id_eintrittsdatum_pk" PRIMARY KEY("member_id","abteilung_id","eintrittsdatum")
);
--> statement-breakpoint
CREATE TABLE "attachments" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"member_id" uuid NOT NULL,
	"filename" text NOT NULL,
	"mime_type" text NOT NULL,
	"size_bytes" bigint NOT NULL,
	"s3_key" text NOT NULL,
	"uploaded_by" text,
	"uploaded_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "attachments_s3_key_unique" UNIQUE("s3_key")
);
--> statement-breakpoint
CREATE TABLE "audit_log" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"actor_id" text,
	"actor_email" text,
	"entity_type" text NOT NULL,
	"entity_id" text NOT NULL,
	"action" "audit_action" NOT NULL,
	"source" "audit_source" DEFAULT 'ui' NOT NULL,
	"changes" jsonb NOT NULL,
	"request_id" text
);
--> statement-breakpoint
CREATE TABLE "accounts" (
	"id" text PRIMARY KEY NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"user_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp with time zone,
	"refresh_token_expires_at" timestamp with time zone,
	"scope" text,
	"password" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "invitations" (
	"id" text PRIMARY KEY NOT NULL,
	"token" text NOT NULL,
	"email" text NOT NULL,
	"role" "user_role" NOT NULL,
	"invited_by" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"accepted_at" timestamp with time zone,
	"revoked_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "invitations_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "sessions" (
	"id" text PRIMARY KEY NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"token" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"user_id" text NOT NULL,
	"impersonated_by" text,
	CONSTRAINT "sessions_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean DEFAULT false NOT NULL,
	"image" text,
	"role" "user_role" DEFAULT 'readonly' NOT NULL,
	"banned" boolean DEFAULT false,
	"ban_reason" text,
	"ban_expires" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "verifications" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "contracts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"member_id" uuid NOT NULL,
	"adr_nr" integer NOT NULL,
	"vertrag_nr" text NOT NULL,
	"art" integer NOT NULL,
	"art_name" text,
	"mitgl_nr" text,
	"sollstellung" text,
	"vertrag_begin" timestamp,
	"vertrag_ende" timestamp,
	"aufnahmegeb" numeric(19, 8),
	"betrag" numeric(19, 8),
	"kuend_anzahl" integer,
	"keund_zeitraum" text,
	"keund_bis" text,
	"gekuend_am" timestamp,
	"gekuend_zum" timestamp,
	"frue_gekuend_am" timestamp,
	"frue_gekuend_zum" timestamp,
	"auto_verl_zahl" integer,
	"auto_verl_zeit" text,
	"auf_rechnung" text,
	"anteilig" text,
	"multipl" integer,
	"steuer" text,
	"abw_adr_nr" integer,
	"verw_zw1" text,
	"verw_zw2" text,
	"verw_zw3" text,
	"verw_zw4" text,
	"lastschrift" text,
	"blz_v" text,
	"bank_v" text,
	"konto_v" text,
	"kto_inh_v" text,
	"monat_ab" integer,
	"rg_nr" integer,
	"prenotifikation" text,
	"abw_konto_inh" text,
	"strasse_kih" text,
	"plz_kih" text,
	"ort_kih" text,
	"email_kih" text,
	"falligkeit_datum1" timestamp,
	"falligkeit_datum2" timestamp,
	"falligkeit_datum3" timestamp,
	"falligkeit_datum4" timestamp,
	"falligkeit_tag" integer,
	"import_batch_id" uuid,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "fee_types" (
	"art" integer NOT NULL,
	"grundlage" text,
	"sollstellung" text,
	"fibukonto" integer,
	"bezeichnung" text,
	"valuta" text,
	"kontoname" text,
	"steuer" text,
	"min_betrag" numeric(19, 8),
	"max_betrag" numeric(19, 8),
	"feld" text,
	"wert" text,
	"anh_art" integer,
	"anh_bez" text,
	"edit" text,
	"soll_nicht_erlaubt" text,
	"spende" text,
	"spendenvorlage" text,
	"ko_st" integer,
	"ko_tr" integer,
	"abteilung" text,
	"e_feld" text,
	"e_min_betrag" numeric(19, 8),
	"e_max_betrag" numeric(19, 8),
	"e_wert" text,
	"e_verkn" text,
	"e_proz" numeric(19, 8),
	"var" text,
	"t_betrag1" numeric(19, 8),
	"t_betrag2" numeric(19, 8),
	"fibukonto1" integer,
	"fibukonto2" integer,
	"ko_st1" integer,
	"ko_st2" integer,
	"falligkeit_datum1" timestamp,
	"falligkeit_datum2" timestamp,
	"falligkeit_datum3" timestamp,
	"falligkeit_datum4" timestamp,
	"falligkeit_tag" integer,
	"ko_st_g" integer,
	"betrag1" numeric(19, 8),
	"nich_aktiv" text,
	"art_type" integer,
	"import_batch_id" text,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "import_batches" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"source" "import_source" NOT NULL,
	"filename" text,
	"file_size_bytes" bigint,
	"members_written" integer DEFAULT 0 NOT NULL,
	"contracts_written" integer DEFAULT 0 NOT NULL,
	"fee_types_written" integer DEFAULT 0 NOT NULL,
	"sepa_written" integer DEFAULT 0 NOT NULL,
	"parsed_tables" text[],
	"skipped_tables" text[],
	"errors" jsonb,
	"started_by" text,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"finished_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "members" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"notes" text,
	"last_imported_at" timestamp with time zone,
	"import_batch_id" uuid,
	"adr_nr" integer NOT NULL,
	"firma1" text,
	"firma2" text,
	"firma3" text,
	"firma4" text,
	"kurzname" text,
	"anrede" text,
	"anrede2" text,
	"anredetitel" text,
	"vorname" text,
	"nachname" text,
	"strasse" text,
	"plz" text,
	"ort" text,
	"lkz" text,
	"postfach_plz" integer,
	"landesvorwahl" integer,
	"vorwahl" text,
	"telefon1" text,
	"telefon2" text,
	"telefon4" text,
	"betreung" text,
	"fax" text,
	"erf_datum" timestamp,
	"adressart" text,
	"letzt_kontakt" timestamp,
	"kennung" text,
	"kontaktwoher" text,
	"widervorlage" timestamp,
	"w_vorl_tage" integer,
	"firma1_rech" text,
	"firma2_rech" text,
	"firma3_rech" text,
	"strasse_rech" text,
	"plz_rech" text,
	"ort_rech" text,
	"plz_rech_postf" text,
	"postach_rech" text,
	"firma1_lief" text,
	"firma2_lief" text,
	"firma3_lief" text,
	"strasse_lief" text,
	"plz_lief" text,
	"ort_lief" text,
	"plz_lief_postf" text,
	"postfach_lief" text,
	"strasse_post" text,
	"plz_post" text,
	"ort_post" text,
	"benutzer" text,
	"bank1" text,
	"blz1" text,
	"konto1" text,
	"bank2" text,
	"blz2" text,
	"konto2" text,
	"bank3" text,
	"blz3" text,
	"konto3" text,
	"kontaktart" text,
	"kunde" text,
	"lieferant" text,
	"interessent" text,
	"and_benutzer" text,
	"and_datum" timestamp,
	"and_zeit" timestamp,
	"am_brief" text,
	"funktion" text,
	"geburtsdatum" timestamp,
	"ini_file" text,
	"ben_erfass" text,
	"ben_aender" text,
	"ben_bemerk" text,
	"ben_kontakt" text,
	"aender_dat" timestamp,
	"zahl_kont" integer,
	"zahl_wied" integer,
	"zahl_bem" integer,
	"ben_wieder" text,
	"nebenadresse" integer,
	"eintritt" timestamp,
	"austritt" timestamp,
	"postzustb" integer,
	"bank" text,
	"blz" text,
	"konto_nr" text,
	"telefon5" text,
	"telefon6" text,
	"telefon7" text,
	"landname" text,
	"land_kurzel" text,
	"finanzamt_nr" integer,
	"bezirk_nr" integer,
	"unter_prf_nr" integer,
	"mahn_sperre" text,
	"lastschrift" text,
	"liefer_nr" text,
	"eg_kenn_nr" text,
	"zahl_spere" text,
	"fibu_nr" integer,
	"mandant" text,
	"lastschr_dat" timestamp,
	"zahlungsart" text,
	"zahlungsweise" text,
	"debitorkto" integer,
	"kreditorkto" integer,
	"mitglnr" text,
	"jahr" integer,
	"serienbrief" text,
	"mitgl_nr_n" integer,
	"aktiv" text,
	"abw_konto_inh" text,
	"check_box1" text,
	"check_box2" text,
	"check_box3" text,
	"bereich" text,
	"buero" text,
	"alt_buero" text,
	"buero_datum" timestamp,
	"kreditkarte" text,
	"kreditkartenhalter" text,
	"kreditkartennummer" text,
	"verfallsdatum" timestamp,
	"kreditkartenname" text,
	"statecode" text,
	"sem_ort" text,
	"referent" text,
	"sem_hotel" text,
	"aktiv_pasiv" text,
	"postfach" integer,
	"telefon3" text,
	"abteilung" text,
	"kennung1" text,
	"kennung2" text,
	"kennung3" text,
	"kennung3_neu" text,
	"mitglied" text,
	"attribut1" text,
	"attribut2" text,
	"attribut3" text,
	"geborene" text,
	"genannt" text,
	"namensvorsatz" text,
	"namenszusatz" text,
	"verstorben_am" timestamp,
	"haupt_kennung" text,
	"titel1" text,
	"titel2" text,
	"spende_kennung" text,
	"check_box4" text,
	"check_box5" text,
	"check_box6" text,
	"check_box7" text,
	"check_box8" text,
	"check_box9" text,
	"check_box10" text,
	"geburtsort" text,
	"e_mail_name" text,
	"rabat_p" numeric(19, 8),
	"rabat_b" numeric(19, 8),
	"mw" text,
	"buero2" text,
	"konto4" text,
	"blz4" text,
	"bank4" text,
	"konto5" text,
	"blz5" text,
	"bank5" text,
	"konto6" text,
	"blz6" text,
	"bank6" text,
	"dauer_spender" text,
	"adr_nr_m" integer,
	"kriterium_hb" text,
	"bundesland" text,
	"bild" text,
	"haus" text,
	"land" text,
	"co" text,
	"landesverband" text,
	"karten_nr1" text,
	"karten_nr2" text,
	"max_kont" integer,
	"versandart" text,
	"gesperrt" text,
	"spender" text,
	"bezirk" text,
	"stadtteil" text,
	"iban1" "bytea",
	"iban1_last4" text,
	"iban2" "bytea",
	"iban3" "bytea",
	"bic1" text,
	"bic2" text,
	"bic3" text,
	"vorwahl2" text,
	"vorwahl3" text,
	"vorwahl4" text,
	"dt_of_sgntr" timestamp,
	"sepa_fe" text,
	"adr_nr_kih" integer,
	"mandatsrefenz" text,
	"dsa_kennziffer" text,
	"dsa_mitgl_nr" text,
	"hausnummer" text,
	"ausweisnummer" text,
	"gueltigkeitsdatum" timestamp,
	"dsa_verband" text,
	"dsa_sport_art" text,
	"dsa_smk" text,
	"dsa_svk" text,
	"dsa_beantragt" text,
	"einzug_last_mand_liegt_vor" text,
	"strasse_kih" text,
	"plz_kih" text,
	"ort_kih" text,
	"email_kih" text,
	"abw_kto_inh_cb" text,
	"abw_anr_ansch" text,
	"adresszusatz" text,
	"briefempfanger" text,
	"briefanrede_s" text,
	"blsv_meldung" timestamp,
	"www" text,
	"einverstandnis_datenverarbeitung" text,
	"veroffentlichung_bild_und_name" text,
	"geburtsname" text,
	"vert_bem" text,
	"post_anschrift_postfach_strasse" text,
	"post_anschrift_postfach_plz" text,
	"post_anschrift_postfach_ort" text,
	"post_anschrift_postfach" text,
	"post_anschrift_memo1" text,
	"post_anschrift_strasse" text,
	"post_anschrift_plz" text,
	"post_anschrift_ort" text,
	"post_anschrift_land" text,
	"post_anschrift_memo2" text,
	"berufs_gruppe" text,
	"einverstandis_datenverarbeitung" text,
	"geloscht" boolean,
	"free_bit1" boolean,
	"free_bit2" boolean,
	"free_text1" text,
	"free_text2" text,
	"free_text3" text,
	"free_text4" text
);
--> statement-breakpoint
CREATE TABLE "sepa_mandates" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"member_id" uuid NOT NULL,
	"adr_nr" integer NOT NULL,
	"mandats_nr" text NOT NULL,
	"mand_key" text,
	"lastschriftart" text,
	"typ" text,
	"status" text,
	"angelegt_am" timestamp,
	"gultig_bis" timestamp,
	"unterschrift_datum" timestamp,
	"erste_verwendung" timestamp,
	"letzte_verwendung" timestamp,
	"widerrufen_am" timestamp,
	"gueltig_ab" timestamp,
	"letzte_verwendung_alt" timestamp,
	"gultig_bis_alt" timestamp,
	"is_deleted" boolean DEFAULT false,
	"import_batch_id" uuid,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "smtp_config" (
	"id" integer PRIMARY KEY DEFAULT 1 NOT NULL,
	"host" text NOT NULL,
	"port" integer NOT NULL,
	"secure" boolean DEFAULT true NOT NULL,
	"username" text,
	"password_encrypted" "bytea",
	"from_address" text NOT NULL,
	"from_name" text,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_by" text
);
--> statement-breakpoint
ALTER TABLE "member_abteilungen" ADD CONSTRAINT "member_abteilungen_member_id_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."members"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "member_abteilungen" ADD CONSTRAINT "member_abteilungen_abteilung_id_abteilungen_id_fk" FOREIGN KEY ("abteilung_id") REFERENCES "public"."abteilungen"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attachments" ADD CONSTRAINT "attachments_member_id_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."members"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attachments" ADD CONSTRAINT "attachments_uploaded_by_users_id_fk" FOREIGN KEY ("uploaded_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit_log" ADD CONSTRAINT "audit_log_actor_id_users_id_fk" FOREIGN KEY ("actor_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "accounts" ADD CONSTRAINT "accounts_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invitations" ADD CONSTRAINT "invitations_invited_by_users_id_fk" FOREIGN KEY ("invited_by") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "contracts" ADD CONSTRAINT "contracts_member_id_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."members"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "import_batches" ADD CONSTRAINT "import_batches_started_by_users_id_fk" FOREIGN KEY ("started_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sepa_mandates" ADD CONSTRAINT "sepa_mandates_member_id_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."members"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "smtp_config" ADD CONSTRAINT "smtp_config_updated_by_users_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "member_abteilungen_member_idx" ON "member_abteilungen" USING btree ("member_id");--> statement-breakpoint
CREATE INDEX "member_abteilungen_abt_idx" ON "member_abteilungen" USING btree ("abteilung_id");--> statement-breakpoint
CREATE INDEX "attachments_member_idx" ON "attachments" USING btree ("member_id");--> statement-breakpoint
CREATE INDEX "audit_entity_idx" ON "audit_log" USING btree ("entity_type","entity_id","created_at");--> statement-breakpoint
CREATE INDEX "audit_created_idx" ON "audit_log" USING btree ("created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "contracts_adrnr_vertragnr_art_uk" ON "contracts" USING btree ("adr_nr","vertrag_nr","art");--> statement-breakpoint
CREATE INDEX "contracts_member_idx" ON "contracts" USING btree ("member_id");--> statement-breakpoint
CREATE UNIQUE INDEX "fee_types_art_uk" ON "fee_types" USING btree ("art");--> statement-breakpoint
CREATE UNIQUE INDEX "members_adr_nr_uk" ON "members" USING btree ("adr_nr");--> statement-breakpoint
CREATE INDEX "members_mitglnr_idx" ON "members" USING btree ("mitglnr");--> statement-breakpoint
CREATE INDEX "members_nachname_vorname_idx" ON "members" USING btree ("nachname","vorname");--> statement-breakpoint
CREATE INDEX "members_email_name_idx" ON "members" USING btree ("e_mail_name");--> statement-breakpoint
CREATE INDEX "members_plz_idx" ON "members" USING btree ("plz");--> statement-breakpoint
CREATE INDEX "members_austritt_idx" ON "members" USING btree ("austritt");--> statement-breakpoint
CREATE INDEX "members_eintritt_idx" ON "members" USING btree ("eintritt");--> statement-breakpoint
CREATE INDEX "members_geloscht_idx" ON "members" USING btree ("geloscht");--> statement-breakpoint
CREATE UNIQUE INDEX "sepa_adrnr_mandatsnr_uk" ON "sepa_mandates" USING btree ("adr_nr","mandats_nr");--> statement-breakpoint
CREATE INDEX "sepa_member_idx" ON "sepa_mandates" USING btree ("member_id");