ALTER TABLE "members" DROP COLUMN "postfach_plz";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "landesvorwahl";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "betreung";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "adressart";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "kennung";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "kontaktwoher";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "w_vorl_tage";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "firma1_rech";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "firma2_rech";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "firma3_rech";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "plz_rech_postf";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "postach_rech";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "firma1_lief";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "firma2_lief";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "firma3_lief";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "plz_lief_postf";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "postfach_lief";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "kontaktart";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "kunde";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "lieferant";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "interessent";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "and_benutzer";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "and_datum";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "and_zeit";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "am_brief";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "ini_file";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "ben_erfass";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "aender_dat";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "zahl_kont";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "zahl_wied";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "zahl_bem";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "nebenadresse";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "postzustb";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "finanzamt_nr";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "bezirk_nr";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "unter_prf_nr";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "liefer_nr";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "eg_kenn_nr";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "zahl_spere";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "fibu_nr";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "mandant";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "lastschr_dat";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "zahlungsart";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "zahlungsweise";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "debitorkto";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "kreditorkto";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "serienbrief";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "mitgl_nr_n";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "check_box1";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "check_box2";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "check_box3";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "bereich";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "buero";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "alt_buero";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "buero_datum";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "statecode";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "sem_ort";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "referent";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "sem_hotel";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "postfach";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "kennung1";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "kennung2";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "kennung3";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "kennung3_neu";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "attribut1";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "attribut2";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "attribut3";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "haupt_kennung";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "spende_kennung";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "check_box4";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "check_box5";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "check_box6";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "check_box7";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "check_box8";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "check_box9";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "check_box10";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "rabat_p";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "rabat_b";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "mw";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "buero2";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "dauer_spender";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "adr_nr_m";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "kriterium_hb";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "landesverband";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "max_kont";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "versandart";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "dt_of_sgntr";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "sepa_fe";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "dsa_kennziffer";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "dsa_mitgl_nr";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "dsa_verband";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "dsa_sport_art";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "dsa_smk";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "dsa_svk";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "dsa_beantragt";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "einzug_last_mand_liegt_vor";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "abw_kto_inh_cb";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "abw_anr_ansch";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "blsv_meldung";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "einverstandnis_datenverarbeitung";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "veroffentlichung_bild_und_name";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "post_anschrift_postfach";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "berufs_gruppe";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "einverstandis_datenverarbeitung";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "free_bit1";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "free_bit2";