ALTER TABLE "members" DROP COLUMN "anrede2";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "anredetitel";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "lkz";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "vorwahl";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "telefon4";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "strasse_rech";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "plz_rech";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "ort_rech";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "strasse_lief";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "plz_lief";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "ort_lief";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "strasse_post";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "plz_post";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "ort_post";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "blz1";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "konto1";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "bank2";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "blz2";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "konto2";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "bank3";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "blz3";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "konto3";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "ben_aender";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "ben_bemerk";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "ben_kontakt";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "ben_wieder";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "konto_nr";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "telefon5";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "telefon6";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "telefon7";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "land_kurzel";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "kreditkarte";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "kreditkartenhalter";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "kreditkartennummer";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "verfallsdatum";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "kreditkartenname";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "konto4";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "blz4";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "bank4";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "konto5";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "blz5";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "bank5";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "konto6";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "blz6";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "bank6";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "bundesland";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "bild";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "co";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "karten_nr1";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "karten_nr2";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "bezirk";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "stadtteil";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "bic2";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "bic3";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "vorwahl2";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "vorwahl3";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "vorwahl4";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "ausweisnummer";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "gueltigkeitsdatum";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "briefempfanger";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "briefanrede_s";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "vert_bem";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "post_anschrift_postfach_strasse";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "post_anschrift_postfach_plz";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "post_anschrift_postfach_ort";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "post_anschrift_memo1";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "post_anschrift_strasse";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "post_anschrift_plz";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "post_anschrift_ort";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "post_anschrift_land";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "post_anschrift_memo2";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "free_text1";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "free_text2";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "free_text3";--> statement-breakpoint
ALTER TABLE "members" DROP COLUMN "free_text4";