import {
  boolean,
  index,
  integer,
  numeric,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";
import { encryptedText } from "~/server/db/types";

/**
 * Explicit gender column (independent of Anrede). Linear's UI uses a similar
 * picklist; storing it separately means we don't lose people whose Anrede is
 * a title ("Dr.", "Prof.") or non-binary form.
 */
export const geschlechtEnum = pgEnum("geschlecht", ["m", "w", "d", "unbekannt"]);

/**
 * Normalized member lifecycle status. Replaces the legacy signals (`aktiv_pasiv`
 * text flag plus the `austritt` / `verstorben_am` dates) with one value derived
 * by `deriveStatus`. Stored, not generated: the importer sets it at the
 * translation boundary and the app keeps it in sync, so it survives the
 * eventual removal of the legacy source columns.
 */
export const memberStatusEnum = pgEnum("member_status", [
  "aktiv",
  "passiv",
  "ausgetreten",
  "verstorben",
]);

/**
 * Lossless mirror of the Linear Webverein `adresse` table (247 columns).
 * Internal `id` is a generated UUID; the Linear `AdrNr` is preserved as a
 * non-null unique integer and `MITGLNR` as the human-readable Mitgliedsnummer.
 * IBAN columns are AES-256-GCM encrypted at rest via the `encryptedText` type.
 * All Linear `char(1)` columns are stored as `text` to match SVUMS (the values
 * are single-letter status codes, not strict booleans). Only true `bit(1)`
 * columns (Geloscht, FreeBit1, FreeBit2) map to `boolean`.
 */
export const membersTable = pgTable(
  "members",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
    notes: text("notes"),
    geschlecht: geschlechtEnum("geschlecht"),
    lastImportedAt: timestamp("last_imported_at", { withTimezone: true }),
    importBatchId: uuid("import_batch_id"),
    adrNr: integer("adr_nr").notNull(),
    firma1: text("firma1"),
    firma2: text("firma2"),
    firma3: text("firma3"),
    firma4: text("firma4"),
    kurzname: text("kurzname"),
    anrede: text("anrede"),
    anrede2: text("anrede2"),
    anredetitel: text("anredetitel"),
    vorname: text("vorname"),
    nachname: text("nachname"),
    strasse: text("strasse"),
    plz: text("plz"),
    ort: text("ort"),
    lkz: text("lkz"),
    postfachPlz: integer("postfach_plz"),
    landesvorwahl: integer("landesvorwahl"),
    vorwahl: text("vorwahl"),
    telefon1: text("telefon1"),
    telefon2: text("telefon2"),
    telefon4: text("telefon4"),
    betreung: text("betreung"),
    fax: text("fax"),
    erfDatum: timestamp("erf_datum", { withTimezone: false }),
    adressart: text("adressart"),
    letztKontakt: timestamp("letzt_kontakt", { withTimezone: false }),
    kennung: text("kennung"),
    kontaktwoher: text("kontaktwoher"),
    widervorlage: timestamp("widervorlage", { withTimezone: false }),
    wVorlTage: integer("w_vorl_tage"),
    firma1Rech: text("firma1_rech"),
    firma2Rech: text("firma2_rech"),
    firma3Rech: text("firma3_rech"),
    strasseRech: text("strasse_rech"),
    plzRech: text("plz_rech"),
    ortRech: text("ort_rech"),
    plzRechPostf: text("plz_rech_postf"),
    postachRech: text("postach_rech"),
    firma1Lief: text("firma1_lief"),
    firma2Lief: text("firma2_lief"),
    firma3Lief: text("firma3_lief"),
    strasseLief: text("strasse_lief"),
    plzLief: text("plz_lief"),
    ortLief: text("ort_lief"),
    plzLiefPostf: text("plz_lief_postf"),
    postfachLief: text("postfach_lief"),
    strassePost: text("strasse_post"),
    plzPost: text("plz_post"),
    ortPost: text("ort_post"),
    benutzer: text("benutzer"),
    bank1: text("bank1"),
    blz1: text("blz1"),
    konto1: text("konto1"),
    bank2: text("bank2"),
    blz2: text("blz2"),
    konto2: text("konto2"),
    bank3: text("bank3"),
    blz3: text("blz3"),
    konto3: text("konto3"),
    kontaktart: text("kontaktart"),
    kunde: text("kunde"),
    lieferant: text("lieferant"),
    interessent: text("interessent"),
    andBenutzer: text("and_benutzer"),
    andDatum: timestamp("and_datum", { withTimezone: false }),
    andZeit: timestamp("and_zeit", { withTimezone: false }),
    amBrief: text("am_brief"),
    funktion: text("funktion"),
    geburtsdatum: timestamp("geburtsdatum", { withTimezone: false }),
    // Custom legal representative (gesetzliche Vertretung) for minors, used as
    // the Mahnung recipient when no connection is flagged as Vertreter. Free
    // text so it works for guardians who are not themselves in the system.
    vertreterAnrede: text("vertreter_anrede"),
    vertreterName: text("vertreter_name"),
    vertreterStrasse: text("vertreter_strasse"),
    vertreterHausnummer: text("vertreter_hausnummer"),
    vertreterPlz: text("vertreter_plz"),
    vertreterOrt: text("vertreter_ort"),
    iniFile: text("ini_file"),
    benErfass: text("ben_erfass"),
    benAender: text("ben_aender"),
    benBemerk: text("ben_bemerk"),
    benKontakt: text("ben_kontakt"),
    aenderDat: timestamp("aender_dat", { withTimezone: false }),
    zahlKont: integer("zahl_kont"),
    zahlWied: integer("zahl_wied"),
    zahlBem: integer("zahl_bem"),
    benWieder: text("ben_wieder"),
    nebenadresse: integer("nebenadresse"),
    eintritt: timestamp("eintritt", { withTimezone: false }),
    austritt: timestamp("austritt", { withTimezone: false }),
    postzustb: integer("postzustb"),
    bank: text("bank"),
    blz: text("blz"),
    kontoNr: text("konto_nr"),
    telefon5: text("telefon5"),
    telefon6: text("telefon6"),
    telefon7: text("telefon7"),
    landname: text("landname"),
    landKurzel: text("land_kurzel"),
    finanzamtNr: integer("finanzamt_nr"),
    bezirkNr: integer("bezirk_nr"),
    unterPrfNr: integer("unter_prf_nr"),
    mahnSperre: text("mahn_sperre"),
    lastschrift: text("lastschrift"),
    lieferNr: text("liefer_nr"),
    egKennNr: text("eg_kenn_nr"),
    zahlSpere: text("zahl_spere"),
    fibuNr: integer("fibu_nr"),
    mandant: text("mandant"),
    lastschrDat: timestamp("lastschr_dat", { withTimezone: false }),
    zahlungsart: text("zahlungsart"),
    zahlungsweise: text("zahlungsweise"),
    debitorkto: integer("debitorkto"),
    kreditorkto: integer("kreditorkto"),
    mitglnr: text("mitglnr"),
    jahr: integer("jahr"),
    serienbrief: text("serienbrief"),
    mitglNrN: integer("mitgl_nr_n"),
    aktiv: text("aktiv"),
    abwKontoInh: text("abw_konto_inh"),
    checkBox1: text("check_box1"),
    checkBox2: text("check_box2"),
    checkBox3: text("check_box3"),
    bereich: text("bereich"),
    buero: text("buero"),
    altBuero: text("alt_buero"),
    bueroDatum: timestamp("buero_datum", { withTimezone: false }),
    kreditkarte: text("kreditkarte"),
    kreditkartenhalter: text("kreditkartenhalter"),
    kreditkartennummer: text("kreditkartennummer"),
    verfallsdatum: timestamp("verfallsdatum", { withTimezone: false }),
    kreditkartenname: text("kreditkartenname"),
    statecode: text("statecode"),
    semOrt: text("sem_ort"),
    referent: text("referent"),
    semHotel: text("sem_hotel"),
    aktivPasiv: text("aktiv_pasiv"),
    postfach: integer("postfach"),
    telefon3: text("telefon3"),
    abteilung: text("abteilung"),
    kennung1: text("kennung1"),
    kennung2: text("kennung2"),
    kennung3: text("kennung3"),
    kennung3Neu: text("kennung3_neu"),
    mitglied: text("mitglied"),
    attribut1: text("attribut1"),
    attribut2: text("attribut2"),
    attribut3: text("attribut3"),
    geborene: text("geborene"),
    genannt: text("genannt"),
    namensvorsatz: text("namensvorsatz"),
    namenszusatz: text("namenszusatz"),
    verstorbenAm: timestamp("verstorben_am", { withTimezone: false }),
    hauptKennung: text("haupt_kennung"),
    titel1: text("titel1"),
    titel2: text("titel2"),
    spendeKennung: text("spende_kennung"),
    checkBox4: text("check_box4"),
    checkBox5: text("check_box5"),
    checkBox6: text("check_box6"),
    checkBox7: text("check_box7"),
    checkBox8: text("check_box8"),
    checkBox9: text("check_box9"),
    checkBox10: text("check_box10"),
    geburtsort: text("geburtsort"),
    eMailName: text("e_mail_name"),
    rabatP: numeric("rabat_p", { precision: 19, scale: 8 }),
    rabatB: numeric("rabat_b", { precision: 19, scale: 8 }),
    mw: text("mw"),
    buero2: text("buero2"),
    konto4: text("konto4"),
    blz4: text("blz4"),
    bank4: text("bank4"),
    konto5: text("konto5"),
    blz5: text("blz5"),
    bank5: text("bank5"),
    konto6: text("konto6"),
    blz6: text("blz6"),
    bank6: text("bank6"),
    dauerSpender: text("dauer_spender"),
    adrNrM: integer("adr_nr_m"),
    kriteriumHb: text("kriterium_hb"),
    bundesland: text("bundesland"),
    bild: text("bild"),
    haus: text("haus"),
    land: text("land"),
    co: text("co"),
    landesverband: text("landesverband"),
    kartenNr1: text("karten_nr1"),
    kartenNr2: text("karten_nr2"),
    maxKont: integer("max_kont"),
    versandart: text("versandart"),
    gesperrt: text("gesperrt"),
    spender: text("spender"),
    bezirk: text("bezirk"),
    stadtteil: text("stadtteil"),
    iban1: encryptedText("iban1"),
    iban1Last4: text("iban1_last4"),
    iban2: encryptedText("iban2"),
    iban3: encryptedText("iban3"),
    bic1: text("bic1"),
    bic2: text("bic2"),
    bic3: text("bic3"),
    vorwahl2: text("vorwahl2"),
    vorwahl3: text("vorwahl3"),
    vorwahl4: text("vorwahl4"),
    dtOfSgntr: timestamp("dt_of_sgntr", { withTimezone: false }),
    sepaFe: text("sepa_fe"),
    adrNrKih: integer("adr_nr_kih"),
    mandatsrefenz: text("mandatsrefenz"),
    dsaKennziffer: text("dsa_kennziffer"),
    dsaMitglNr: text("dsa_mitgl_nr"),
    hausnummer: text("hausnummer"),
    ausweisnummer: text("ausweisnummer"),
    gueltigkeitsdatum: timestamp("gueltigkeitsdatum", { withTimezone: false }),
    dsaVerband: text("dsa_verband"),
    dsaSportArt: text("dsa_sport_art"),
    dsaSmk: text("dsa_smk"),
    dsaSvk: text("dsa_svk"),
    dsaBeantragt: text("dsa_beantragt"),
    einzugLastMandLiegtVor: text("einzug_last_mand_liegt_vor"),
    strasseKih: text("strasse_kih"),
    plzKih: text("plz_kih"),
    ortKih: text("ort_kih"),
    emailKih: text("email_kih"),
    abwKtoInhCb: text("abw_kto_inh_cb"),
    abwAnrAnsch: text("abw_anr_ansch"),
    adresszusatz: text("adresszusatz"),
    briefempfanger: text("briefempfanger"),
    briefanredeS: text("briefanrede_s"),
    blsvMeldung: timestamp("blsv_meldung", { withTimezone: false }),
    www: text("www"),
    einverstandnisDatenverarbeitung: text("einverstandnis_datenverarbeitung"),
    veroffentlichungBildUndName: text("veroffentlichung_bild_und_name"),
    geburtsname: text("geburtsname"),
    vertBem: text("vert_bem"),
    postAnschriftPostfachStrasse: text("post_anschrift_postfach_strasse"),
    postAnschriftPostfachPlz: text("post_anschrift_postfach_plz"),
    postAnschriftPostfachOrt: text("post_anschrift_postfach_ort"),
    postAnschriftPostfach: text("post_anschrift_postfach"),
    postAnschriftMemo1: text("post_anschrift_memo1"),
    postAnschriftStrasse: text("post_anschrift_strasse"),
    postAnschriftPlz: text("post_anschrift_plz"),
    postAnschriftOrt: text("post_anschrift_ort"),
    postAnschriftLand: text("post_anschrift_land"),
    postAnschriftMemo2: text("post_anschrift_memo2"),
    berufsGruppe: text("berufs_gruppe"),
    einverstandisDatenverarbeitung: text("einverstandis_datenverarbeitung"),
    geloscht: boolean("geloscht"),
    freeBit1: boolean("free_bit1"),
    freeBit2: boolean("free_bit2"),
    freeText1: text("free_text1"),
    freeText2: text("free_text2"),
    freeText3: text("free_text3"),
    freeText4: text("free_text4"),
    // --- Clean, app-owned columns (Phase 1) ---------------------------------
    // These hold the normalized shape produced by `translateLinearMember`.
    // They are backfilled from the legacy columns above and coexist with them
    // until consumers are cut over; nothing reads them yet. See
    // `~/server/domain/member` for the canonical derivations.
    /** Clean name for the legacy `mitglnr`. The human-readable member number. */
    mitgliedsnummer: text("mitgliedsnummer"),
    /** Clean name for `e_mail_name`, with the legacy `telefon3` fallback. */
    email: text("email"),
    /** Normalized lifecycle status (was `aktiv_pasiv` + the exit/death dates). */
    status: memberStatusEnum("status"),
    /** Normalized dunning block (was the free-form `mahn_sperre` text flag). */
    dunningBlocked: boolean("dunning_blocked").notNull().default(false),
  },
  (t) => [
    uniqueIndex("members_adr_nr_uk").on(t.adrNr),
    index("members_mitglnr_idx").on(t.mitglnr),
    index("members_nachname_vorname_idx").on(t.nachname, t.vorname),
    index("members_email_name_idx").on(t.eMailName),
    index("members_plz_idx").on(t.plz),
    index("members_austritt_idx").on(t.austritt),
    index("members_eintritt_idx").on(t.eintritt),
    index("members_geloscht_idx").on(t.geloscht),
    index("members_mitgliedsnummer_idx").on(t.mitgliedsnummer),
    index("members_status_idx").on(t.status),
  ],
);

export type Member = typeof membersTable.$inferSelect;
export type NewMember = typeof membersTable.$inferInsert;
